version: '3'
services:
  app:
    image: hw/liba
    ports:
      - "8080:8080" 
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    networks:
      - lib-nw
  postgres-liba:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=liba
    networks:
      - lib-nw
networks:
  lib-nw:
